### ISSUE TITLE
`Closing WebSocket Connection` log

### ISSUE THREAD

**Issue by mahjiang** [floating/eth-provider#14]
It looks like a [recent commit](https://github.com/floating/eth-provider/commit/5839ebd71d76a73318db5cad36db7d6ba0117dda#diff-b82712e217a01f537d335ce48991a64aR38) introduced a new `console.log` anytime `process.env.NODE_ENV !== 'development'`. Using the `development` environment will turn that log off but cause this to get logged instead:

```
A connection cycle started for provider with name: default
Successfully connected to: ws://127.0.0.1:8546
```

**Comment by floating** [comment]
Sorry about that, all of these logs should only appear when in development env. Thanks!
