### ISSUE TITLE
ws connection 'connect' event firing before provider is connected

### ISSUE THREAD

**Issue by mahjiang** [floating/eth-provider#16]
It appears that the ['connect' event](https://github.com/floating/eth-provider/blob/master/connections/ws.js#L18) is being emitted before its provider is `connected`.

If I create a new `Web3` instance as such:
```
const provider = require('eth-provider')
const Web3 = require('web3')
const web3Instance = new Web3(provider('ws://127.0.0.1:8546'))
web3Instance.currentProvider.connection.once('connect', () => {
  console.log(web3Instance)
})
```

The log output shows the provider as `connected: false` and `status: loading`

I believe the expected behavior should be that the 'connect' event is emitted iff the provider is connected and usable.

Let me know if I can help or if my understanding is incorrect. Thanks!

**Comment by mahjiang** [comment]
Ah okay. I see, that makes sense.

I will update my code to listen to the provider's connect event and will keep an eye out for your update as well.

Thanks so much for your responsiveness!

**Comment by floating** [comment]
@mahjiang Sorry for the delay, I have been busy working on a new Frame release. I just revisited this issue and it seems that the connect flag is working correctly after all. It is being set prior to the connect event as long as you're listening to the provider's connect event and not its underlying connection's event.

If I missed something or you're still having this issue be sure to let me know!

**Comment by mahjiang** [comment]
@floating No problem at all! Everything has been working fine for me based on your previous suggestion, so I think we're good to go.

Thank you!
