### ISSUE TITLE
Ethereum providers may not be EventEmitters

### ISSUE THREAD

**Issue by sohkai** [floating/eth-provider#19]
[Line causing crashes](https://github.com/floating/eth-provider/blob/master/provider/index.js#L7).

Although [EIP-1193 loosely defines events as being emitted through `EventEmitter`](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md#events), there is no actual hard spec that says the `window.ethereum` object _must_ be an `EventEmitter` implementation (nor which API version).

This has lead to some environments where the `window.ethereum` object doesn't implement an `emit()` API (e.g. Status), and thus crashes `eth-provider`.

Furthermore, it seems like this bit of code (`monitor()`) only serves to add a few additional events to the provider which are not included in EIP-1193 and are not used internally at all. I assume Frame uses these events?

**Comment by floating** [comment]
Hey sohkai, I will push a fix for this shortly. 

Yes, monitor is a small bit of functionality that tests if a node is syncing. I will make this opt-in in the future.

**Comment by floating** [comment]
Fixed and published, install `eth-provider@0.2.0`
