### ISSUE TITLE
Next EIP1193 call

### ISSUE THREAD

**Issue by alcuadrado** [floating/eth-provider#24]
Hi @floating,

I'm opening this issue because between a few interested parties we had an open call today to discuss possible changes on EIP1193 and its release schedule. The call wasn't very representative, so nothing was decided, and we are scheduling another one. 

As you are the author of this library and Frame, I think you may be interested in joining the next call, or the [discord channel](https://discord.gg/J4WHas) where this is being discussed. There are also some interesting discussions going on on [ethereum magicians provider ring](https://ethereum-magicians.org/c/working-groups/provider-ring), and you may want to check them.

Best,
Patricio

**Comment by floating** [comment]
Hey Patricio, thanks for reaching out! 

I'd love to join in the discussions and will do my best to join the next call. Discord is telling me the invite link is invalid. I will check out the discussions in the provider ring in the meantime.

Jordan

**Comment by alcuadrado** [comment]
I guess it expired. Here's a new one: https://discord.gg/wGEDrV

**Comment by floating** [comment]
Both `eth-provider` and `ethereum-provider` were updated a couple weeks ago to adhere to the final EIP-1193 spec. Thanks for all your work on that, I'd love to stay involved going forward.

**Comment by alcuadrado** [comment]
That's great new @floating! Thanks for updating them.
